String manipulation 2 | Max
Korneliu/c1021-code-solutions pull request #56
Opened 2021-11-01 16:18 UTC by Korneliu

![string-manipulation-2](https://user-images.githubusercontent.com/25681013/139704707-1db48008-92dc-46ae-8abe-a51adc2076a3.png)

2021-11-02 23:34 UTC, codingcodymiller requested changes

2021-11-02 23:34 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +    return 'JavaScript';
You should do this conditional before anything else in the function, that way you don't do a bunch of stuff that ends up being useless if the value was `"javascript"`

2021-11-02 23:34 UTC, codingcodymiller commented on string-manipulation-2/src/capitalize-word.js
> +  result = upperCaseLetter.concat(resultOfSlice);
You can just do these on the same line you make the variable

2021-11-03 05:35 UTC, Korneliu commented
![string-manipulation-2](https://user-images.githubusercontent.com/25681013/140014099-ec0b8733-7e60-430a-ba1f-5ed8f8baf2b1.png)

2021-11-03 22:33 UTC, codingcodymiller approved these changes

2021-11-04 04:34 UTC, merged